const industryLabelMap = {
  dashboard: "Overview",
  projects: "Services",
  project: "Service",
  clients: "Customers",
  client: "Customer",
  leads: "Customers",
  lead: "Customer",
  positiveClients: "Priority Customers",
  followups: "Follow-ups / Reminders",
  followup: "Reminder",
  siteVisits: "Appointments",
  siteVisit: "Appointment",
  deals: "Billing / Invoices",
  deal: "Invoice",
  dealReports: "Salon Reports",
  reports: "Salon Reports",
  users: "Staff",
  user: "Staff Member",
  settings: "Settings",
  booking: "Booking",
  negotiation: "Consultation",
  revenue: "Revenue",
  summary: "Summary",
};

export const industryLabels = {
  appName: "Salon CRM",
  brandName: "Lavista Salon",
  brandTagline: "Appointment-first customer management",
  footerTitle: "Salon CRM System",
  footerDescription: "Manage customers, services, appointments, reminders, billing, and staff.",
  billing: "Billing / Invoices",
  breadcrumbs: {
    dashboard: "Overview",
    projects: "Services",
    clients: "Customers",
    leads: "Customers",
    followups: "Follow-ups / Reminders",
    reminders: "Follow-ups / Reminders",
    reports: "Salon Reports",
    settings: "Settings",
    users: "Staff",
    deals: "Billing / Invoices",
    siteVisits: "Appointments",
  },
  navigation: {
    overview: "Overview",
    services: "Services",
    addService: "Add Service",
    customers: "Customers",
    priorityCustomers: "Priority Customers",
    addCustomer: "Add Customer",
    reminders: "Follow-ups / Reminders",
    appointments: "Appointments",
    consultations: "Consultations",
    bookings: "Bookings",
    closedInvoices: "Closed Invoices",
    billing: "Billing / Invoices",
    salonReports: "Salon Reports",
    sharedHistory: "Shared History",
    settings: "Settings",
  },
  dashboard: {
    customers: "Customers",
    services: "Services",
    appointments: "Appointments",
    billing: "Billing / Invoices",
    reminders: "Follow-ups / Reminders",
    salonReports: "Salon Reports",
  },
  actions: {
    addCustomer: "Add Customer",
    addService: "Add Service",
    addAppointment: "Add Appointment",
    addInvoice: "Add Invoice",
    createCustomer: "Create Customer",
    createService: "Create Service",
    createAppointment: "Create Appointment",
    createInvoice: "Create Invoice",
    updateCustomer: "Update Customer",
    updateService: "Update Service",
    updateAppointment: "Update Appointment",
    updateInvoice: "Update Invoice",
  },
};

export const getIndustryLabel = (key, fallback = "") => industryLabelMap[key] || fallback || key;
